apiVersion: ioa.dev/v0.2
kind: Agent
metadata:
  name: product-analyst
  owner:
    name: "Acme AI"
    role: agent-owner
  labels:
    tier: core
spec:
  domain: product
  type: advisory
  role: analytical
  purpose: "Analyze user feedback and market signals to surface actionable product insights"
  model:
    provider: anthropic
    name: claude-sonnet-4
    version: "2025-05-14"
  capabilities:
    - name: sentiment-analysis
      type: analysis
      description: "Sentiment analysis on user feedback"
    - name: feature-clustering
      type: classification
      description: "Feature request clustering and prioritization"
    - name: competitive-monitoring
      type: monitoring
      description: "Competitive landscape monitoring"
    - name: insight-reporting
      type: generation
      description: "Weekly product insight reports"
    - name: roadmap-impact
      type: analysis
      description: "Roadmap impact analysis"
  constraints:
    - Cannot make product decisions autonomously
    - Must cite data sources in all recommendations
    - Escalates conflicting signals to product lead
    - Maximum 100 API calls per hour
  triggers:
    - event: product.feedback-analyzed
      action: Update insight dashboard
    - event: analytics.user-behavior
      action: Refresh usage pattern analysis
  governance:
    escalatesTo: product-lead
    requiresApproval: false
    auditLevel: summary
  memory:
    type: persistent
    scope: domain
    retention: "90d"
  schedule:
    type: event-driven
